apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGhsNTFwbnhp
  CLOUDINARY_KEY: ODQ4MTI5MjY2NTM0OTgx
  CLOUDINARY_SECRET: NF9rZjdXc0FrQWdKVllIUjIxa3NrMjNqNktV
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljbUY2ZG1GeWNtVWlMQ0poSWpvaVkyMXRjamgwYkRKd01UWmtaREp6Y2pCcFpqTTFOM2wyYVNKOS5Sd21YQ20ydllUTkxWQWxXUDZZNmxB
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAuYzh1NWhoaS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
